import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatListModule, 
  MatButtonModule, 
  MatIconModule, 
  MatLineModule, 
  MatMenuModule, 
  MatToolbarModule, 
  MatExpansionModule, 
  MatCardModule,
  MatInputModule,
  MatTableModule,
  MatPaginatorModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatSelectModule,
} from '@angular/material';

@NgModule({
  imports: [ MatListModule, 
    MatButtonModule, 
    MatIconModule, 
    MatLineModule, 
    MatMenuModule, 
    MatToolbarModule, 
    MatExpansionModule, 
    MatCardModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSelectModule,
  ],
  exports: [ MatListModule, 
    MatButtonModule,
    MatIconModule, 
    MatLineModule, 
    MatMenuModule, 
    MatToolbarModule, 
    MatExpansionModule, 
    MatCardModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSelectModule,
  ],
})
export class MaterialModule { }